
services:
  proxy:
    image: nginx:latest
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    restart: always

  server:
    build:
      context: .
      dockerfile: server.Dockerfile
    environment:
      - DOCKER=TRUE
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    working_dir: /app
